version: 0.2

phases:
  install:
    commands:
      - node --version
      - npm --version
      - npm install

  pre_build:
    commands:
      - echo "Pre-build phase"
      - node --version

  build:
    commands:
      - echo "Building React application..."
      - NODE_OPTIONS=--openssl-legacy-provider npm run build

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  base-directory: build
  files:
    - '**/*'
